'use client'

import React from 'react'

export default function PrivacyPolicy() {
    return (
        <main className="min-h-screen bg-[var(--bg-primary)] py-16 px-4 md:px-8">
            <div className="max-w-4xl mx-auto">
                <h1 className="text-4xl font-bold mb-3 text-[var(--text-primary)]">Privacy Policy</h1>
                <p className="text-[var(--text-secondary)] mb-12">Last Updated: 15-Dec-2025</p>

                <div className="prose prose-invert max-w-none text-[var(--text-secondary)] prose-headings:text-[var(--text-primary)] prose-a:text-[var(--gold-primary)]">
                    <p>
                        ApexNeural Private Limited (“ApexNeural”, “we”, “us”, “our”) respects your privacy and is committed to protecting your personal data. This Privacy Policy describes how we collect, use, store, share, and protect your information in accordance with the Digital Personal Data Protection Act, 2023 (DPDP Act), the Information Technology Act, 2000, the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 (SPDI Rules), and other applicable laws.
                    </p>
                    <p>
                        This Privacy Policy applies to your use of this website, its related domains, subdomains, product-specific websites, mobile applications, APIs, dashboards, AI or machine-learning tools, and any related services operated by ApexNeural (collectively, the “Platform” or “Services”).
                    </p>
                    <p>
                        This website and all related product websites, domains, and subdomains are owned and operated by ApexNeural Private Limited, unless explicitly stated otherwise.
                    </p>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">1. Personal Data We Collect</h2>

                    <h3 className="text-xl font-semibold mt-6 mb-2">1.1 Data Provided by You</h3>
                    <p>When you use our Platform, you may voluntarily provide:</p>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>Full name, email address, phone number, and company name</li>
                        <li>Login or account registration details</li>
                        <li>Billing and payment information (if you purchase paid plans)</li>
                        <li>Files, text, documents, datasets, media or any content uploaded by you (“User Content”) including legal case files, contracts, pleadings, and research queries.</li>
                    </ul>

                    <h3 className="text-xl font-semibold mt-6 mb-2">1.2 Data Collected Automatically</h3>
                    <p>We automatically collect:</p>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>IP address, device and browser type, operating system</li>
                        <li>Usage metrics such as pages visited, actions performed, features used, session duration</li>
                        <li>Cookies, pixel tags, web beacons and similar tracking technologies (See Section 10)</li>
                    </ul>

                    <h3 className="text-xl font-semibold mt-6 mb-2">1.3 Data Generated by Our AI Services</h3>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>Inputs submitted to our AI systems</li>
                        <li>Outputs generated by the Platform in response to your inputs</li>
                        <li>Conversation history, customization preferences, and feedback</li>
                    </ul>

                    <h3 className="text-xl font-semibold mt-6 mb-2">1.4 Definition of Personal Data</h3>
                    <p>
                        “Personal data” means any data relating to an identifiable individual. It does not include anonymized or aggregated data that cannot identify you.
                    </p>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">2. Lawful Basis for Processing</h2>
                    <p>
                        Under the Digital Personal Data Protection Act, 2023 (DPDP Act) and other applicable laws, we process personal data based on one or more of the following lawful grounds:
                    </p>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>your consent.</li>
                        <li>performance of a contract or provision of requested Services.</li>
                        <li>legitimate business purposes, including security, analytics, research, service improvement, fraud prevention, and internal operations.</li>
                        <li>compliance with legal or regulatory obligations.</li>
                    </ul>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">3. User Responsibility for Uploaded Content</h2>
                    <p>
                        You are responsible for ensuring that any User Content, including documents, images, datasets, or files uploaded to the Platform:
                    </p>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>does not infringe the privacy or rights of others,</li>
                        <li>does not contain personal data of any individual without lawful authorization or consent.</li>
                    </ul>
                    <p>Uploading sensitive or illegal content is strictly prohibited.</p>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">4. How We Use Your Data</h2>
                    <p>We use personal data to:</p>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>Provide, operate, maintain and improve our Services</li>
                        <li>Personalize user experience and AI outputs</li>
                        <li>Manage payments, billing, and account services</li>
                        <li>Communicate with you (support, alerts, service updates, newsletters if you opt-in)</li>
                        <li>Monitor usage patterns and enhance platform performance</li>
                        <li>Detect, prevent, and mitigate fraud, abuse, or security threats</li>
                        <li>Conduct research or analytics without identifying individuals</li>
                        <li>Train, tune, evaluate, and improve artificial intelligence and machine-learning models</li>
                        <li>Perform internal analytics, benchmarking, and business intelligence</li>
                        <li>Develop new products, features, and services</li>
                        <li>Comply with applicable laws, legal requests, or regulatory requirements</li>
                    </ul>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">5. Use of Data for AI Training</h2>
                    <p>
                        5.1 By default, User Content, inputs, outputs, and interaction data may be used to train, tune, evaluate, and improve our artificial intelligence and machine-learning models, unless you opt out where such option is provided.
                    </p>
                    <p>
                        5.2 We take reasonable steps to avoid using data that directly identifies individuals for model training, unless such use is permitted under applicable law or based on your consent.
                    </p>
                    <p>
                        5.3 You may opt out of training use anytime by:
                    </p>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>Using account settings, or</li>
                        <li>Emailing <a href="mailto:info@apexneural.com">info@apexneural.com</a> with subject: “Opt-Out of Model Training”</li>
                    </ul>
                    <p>
                        5.4 Anonymized or aggregated data that cannot identify you may still be retained or used for improvement.
                    </p>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">6. Automated Decision-Making & Disclaimer</h2>
                    <p>
                        Our AI-powered systems may generate recommendations or insights based on your inputs. No legally significant decisions are made solely through automated processing. Outputs should not be treated as professional advice without independent human review.
                    </p>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">7. Sharing & Disclosure of Personal Data</h2>
                    <p>We do not sell personal data. We share data only with:</p>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>Cloud hosting providers and data processors (with equivalent or higher protection obligations)</li>
                        <li>Payment processors and fraud prevention partners</li>
                        <li>Professional advisors, attorneys, auditors, or insurers where necessary</li>
                        <li>Governmental or regulatory authorities if legally required</li>
                        <li>Third parties in case of merger, acquisition, or business transfer (data will continue under this Policy)</li>
                    </ul>
                    <p>
                        All third-party processors act only under our instructions and legal agreements. We may also share anonymized or aggregated data that does not identify individuals for research, analytics, business insights, or product improvement purposes.
                    </p>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">8. International Transfers</h2>
                    <p>
                        Your data is primarily stored and processed in India. If transferred outside India, we ensure adequate safeguards consistent with DPDP Act standards and applicable international requirements.
                    </p>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">9. Data Security</h2>
                    <p>We implement industry-standard organizational and technical controls, including:</p>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>Encryption at rest (AES-256 where applicable)</li>
                        <li>Encryption in transit (TLS/SSL)</li>
                        <li>Access control and authentication procedures</li>
                        <li>Regular vulnerability assessment and monitoring</li>
                    </ul>
                    <p>However, no electronic transmission or storage method is 100% secure.</p>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">10. Cookies & Tracking Technologies</h2>
                    <p>We use:</p>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>Essential cookies (required for site functionality)</li>
                        <li>Optional analytics cookies (e.g., Google Analytics / Plausible)</li>
                    </ul>
                    <p>Optional cookies are used only with your consent. You may manage preferences via browser settings or cookie banner.</p>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">11. Data Retention</h2>
                    <p>
                        We retain personal data for as long as reasonably necessary to fulfill the purposes described in this Policy, including operational, analytical, research, development, security, compliance, and legal purposes.
                    </p>
                    <div className="overflow-x-auto">
                        <table className="w-full text-left border-collapse my-4">
                            <thead>
                                <tr className="border-b border-[var(--border-light)]">
                                    <th className="py-2">Category</th>
                                    <th className="py-2">Retention Duration</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr className="border-b border-[var(--border-light)]">
                                    <td className="py-2 pr-4">Account data</td>
                                    <td className="py-2">Until account deletion + up to 180 days</td>
                                </tr>
                                <tr className="border-b border-[var(--border-light)]">
                                    <td className="py-2 pr-4">Billing & tax records</td>
                                    <td className="py-2">8 years (legal requirement)</td>
                                </tr>
                                <tr className="border-b border-[var(--border-light)]">
                                    <td className="py-2 pr-4">Inputs/Outputs</td>
                                    <td className="py-2">Until deleted by you or you opt-out</td>
                                </tr>
                                <tr className="border-b border-[var(--border-light)]">
                                    <td className="py-2 pr-4">Logs & analytics</td>
                                    <td className="py-2">Up to 12 months</td>
                                </tr>
                                <tr className="border-b border-[var(--border-light)]">
                                    <td className="py-2 pr-4">Legal disputes/compliance</td>
                                    <td className="py-2">As required for protection or claims</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <p>Anonymized or aggregated data that cannot reasonably identify an individual may be retained indefinitely.</p>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">12. Your Rights Under DPDP Act</h2>
                    <p>You have the right to:</p>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>Access your personal data</li>
                        <li>Request corrections or updating of inaccurate data</li>
                        <li>Withdraw consent (where processing is consent-based)</li>
                        <li>Request deletion (subject to legal exceptions)</li>
                        <li>Nominate a person to exercise rights on your behalf in case of death/incapacity</li>
                        <li>File a complaint with the Data Protection Board of India</li>
                    </ul>
                    <p>
                        To exercise rights, email: <a href="mailto:info@apexneural.com">info@apexneural.com</a><br />
                        Subject: “DPDP Rights Request”
                    </p>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">13. Personal Data Breach Notification</h2>
                    <p>
                        In case of a personal data breach affecting your rights, we will notify:
                        <br />
                        • You (where required by law), and
                        <br />
                        • The Data Protection Board of India, in accordance with legal obligations.
                    </p>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">14. Children’s Privacy</h2>
                    <p>
                        Our Services are not intended for individuals under 18 years of age. We do not knowingly collect data from children. If inadvertently collected, we will delete it upon request.
                    </p>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">15. Grievance Officer</h2>
                    <p>
                        Name: S.B.Rao<br />
                        Designation: Grievance Officer<br />
                        Email: <a href="mailto:grievance@apexneural.com">grievance@apexneural.com</a><br />
                        Phone: +91-98499 49597<br />
                        Address:<br />
                        ApexNeural Private Limited,<br />
                        5th Floor, Shantha Sriram Building, PRS Towers,<br />
                        Gachibowli, K.V. Rangareddy,<br />
                        Telangana, India – 500032
                    </p>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>We will acknowledge grievances within 7 days</li>
                        <li>We will aim to resolve them within 30 days</li>
                    </ul>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">16. Updates to This Policy</h2>
                    <p>
                        We may update this Privacy Policy periodically. If material changes are made, we will notify you via email or a prominent notice on the Platform. Continued use of the applicable Website or Services after such updates constitutes acceptance of the revised Privacy Policy.
                    </p>

                    <h2 className="text-2xl font-semibold mt-10 mb-4">17. Contact Us</h2>
                    <p>
                        For privacy questions or concerns:<br />
                        <a href="mailto:info@apexneural.com">info@apexneural.com</a>
                    </p>
                    <p>
                        Registered Address:<br />
                        ApexNeural Private Limited<br />
                        5th Floor, Shantha Sriram Building, PRS Towers,<br />
                        Gachibowli, K.V. Rangareddy,<br />
                        Telangana, India – 500032<br />
                        CIN: U62013TS2024PTC189416
                    </p>
                    <p>
                        This Privacy Policy applies to all websites and platforms operated by ApexNeural unless a separate privacy policy is explicitly provided.
                    </p>
                </div>

                <div className="mt-16 pt-8 border-t border-[var(--border-light)] text-center text-sm text-[var(--text-tertiary)]">
                    &copy; 2025 ApexNeural. All rights reserved.
                </div>
            </div>
        </main>
    )
}
