"""check_pending_changes

Revision ID: 3926d51d6f0f
Revises: c7d1e8f2a3b4
Create Date: 2026-01-29 10:24:59.810014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3926d51d6f0f'
down_revision: Union[str, None] = 'c7d1e8f2a3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ocr_chunks_document'), table_name='ocr_chunks')
    op.drop_index(op.f('idx_ocr_chunks_embeddable'), table_name='ocr_chunks')
    op.drop_index(op.f('idx_ocr_chunks_pages'), table_name='ocr_chunks')
    op.drop_constraint(op.f('uq_ocr_chunks_doc_seq'), 'ocr_chunks', type_='unique')
    op.create_index(op.f('ix_ocr_chunks_document_id'), 'ocr_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_ocr_chunks_is_embeddable'), 'ocr_chunks', ['is_embeddable'], unique=False)
    op.alter_column('ocr_documents', 'ocr_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('idx_ocr_documents_hash'), table_name='ocr_documents')
    op.drop_index(op.f('idx_ocr_documents_matter'), table_name='ocr_documents')
    op.drop_index(op.f('idx_ocr_documents_status'), table_name='ocr_documents')
    op.drop_constraint(op.f('ocr_documents_file_hash_key'), 'ocr_documents', type_='unique')
    op.create_index(op.f('ix_ocr_documents_file_hash'), 'ocr_documents', ['file_hash'], unique=True)
    op.drop_index(op.f('idx_ocr_pages_confidence'), table_name='ocr_pages')
    op.drop_index(op.f('idx_ocr_pages_document'), table_name='ocr_pages')
    op.drop_constraint(op.f('uq_ocr_pages_doc_page'), 'ocr_pages', type_='unique')
    op.create_index(op.f('ix_ocr_pages_document_id'), 'ocr_pages', ['document_id'], unique=False)
    op.drop_index(op.f('idx_ocr_log_document'), table_name='ocr_processing_log')
    op.drop_index(op.f('idx_ocr_log_step'), table_name='ocr_processing_log')
    op.create_index(op.f('ix_ocr_processing_log_document_id'), 'ocr_processing_log', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_processing_log_document_id'), table_name='ocr_processing_log')
    op.create_index(op.f('idx_ocr_log_step'), 'ocr_processing_log', ['step_name'], unique=False)
    op.create_index(op.f('idx_ocr_log_document'), 'ocr_processing_log', ['document_id'], unique=False)
    op.drop_index(op.f('ix_ocr_pages_document_id'), table_name='ocr_pages')
    op.create_unique_constraint(op.f('uq_ocr_pages_doc_page'), 'ocr_pages', ['document_id', 'page_number'])
    op.create_index(op.f('idx_ocr_pages_document'), 'ocr_pages', ['document_id'], unique=False)
    op.create_index(op.f('idx_ocr_pages_confidence'), 'ocr_pages', ['ocr_confidence'], unique=False)
    op.drop_index(op.f('ix_ocr_documents_file_hash'), table_name='ocr_documents')
    op.create_unique_constraint(op.f('ocr_documents_file_hash_key'), 'ocr_documents', ['file_hash'])
    op.create_index(op.f('idx_ocr_documents_status'), 'ocr_documents', ['ocr_status'], unique=False)
    op.create_index(op.f('idx_ocr_documents_matter'), 'ocr_documents', ['matter_id'], unique=False)
    op.create_index(op.f('idx_ocr_documents_hash'), 'ocr_documents', ['file_hash'], unique=True)
    op.alter_column('ocr_documents', 'ocr_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_ocr_chunks_is_embeddable'), table_name='ocr_chunks')
    op.drop_index(op.f('ix_ocr_chunks_document_id'), table_name='ocr_chunks')
    op.create_unique_constraint(op.f('uq_ocr_chunks_doc_seq'), 'ocr_chunks', ['document_id', 'chunk_sequence'])
    op.create_index(op.f('idx_ocr_chunks_pages'), 'ocr_chunks', ['source_page_start', 'source_page_end'], unique=False)
    op.create_index(op.f('idx_ocr_chunks_embeddable'), 'ocr_chunks', ['is_embeddable'], unique=False)
    op.create_index(op.f('idx_ocr_chunks_document'), 'ocr_chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###
